version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_expenses
    restart: always
    environment:
      POSTGRES_USER: traking
      POSTGRES_PASSWORD: traking123
      POSTGRES_DB: expenses_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
        - pg_expenses
volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
